// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type PermType string

const (
	PermTypeManageBook  PermType = "ManageBook"
	PermTypeCreateBook  PermType = "CreateBook"
	PermTypeManageUsers PermType = "ManageUsers"
)

func (e *PermType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PermType(s)
	case string:
		*e = PermType(s)
	default:
		return fmt.Errorf("unsupported scan type for PermType: %T", src)
	}
	return nil
}

type NullPermType struct {
	PermType PermType `json:"PermType"`
	Valid    bool     `json:"valid"` // Valid is true if PermType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPermType) Scan(value interface{}) error {
	if value == nil {
		ns.PermType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PermType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPermType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PermType), nil
}

type AuthorLevel struct {
	ID        int16  `json:"id"`
	LevelName string `json:"level_name"`
}

type AuthorTitle struct {
	ID      int16  `json:"id"`
	GenreID int16  `json:"genre_id"`
	Title   string `json:"title"`
}

type AuthorType struct {
	ID       int16  `json:"id"`
	GenreID  int16  `json:"genre_id"`
	TypeName string `json:"type_name"`
}

type Book struct {
	ID        int64          `json:"id"`
	AuthorID  int64          `json:"author_id"`
	Title     string         `json:"title"`
	Subtitle  sql.NullString `json:"subtitle"`
	CreatedAt time.Time      `json:"created_at"`
}

type Chapter struct {
	ID        int64          `json:"id"`
	BookID    int64          `json:"book_id"`
	Name      string         `json:"name"`
	Content   sql.NullString `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
}

type Character struct {
	ID                  int64          `json:"id"`
	BookID              int64          `json:"book_id"`
	Description         sql.NullString `json:"description"`
	Age                 sql.NullString `json:"age"`
	Gender              sql.NullString `json:"gender"`
	DateOfBirth         sql.NullString `json:"date_of_birth"`
	Job                 sql.NullString `json:"job"`
	JobSatisfaction     sql.NullString `json:"job_satisfaction"`
	Health              sql.NullString `json:"health"`
	Relationships       sql.NullString `json:"relationships"`
	Pets                sql.NullString `json:"pets"`
	World               sql.NullString `json:"world"`
	AreaOfResidence     sql.NullString `json:"area_of_residence"`
	Neighbourhood       sql.NullString `json:"neighbourhood"`
	HomeDescription     sql.NullString `json:"home_description"`
	Height              sql.NullString `json:"height"`
	Weight              sql.NullString `json:"weight"`
	Ethnicity           sql.NullString `json:"ethnicity"`
	SkinTone            sql.NullString `json:"skin_tone"`
	EyeColor            sql.NullString `json:"eye_color"`
	DistinguishFeature  sql.NullString `json:"distinguish_feature"`
	OtherFacialFeatures sql.NullString `json:"other_facial_features"`
	Hairstyle           sql.NullString `json:"hairstyle"`
	BodyType            sql.NullString `json:"body_type"`
	ClothingStyle       sql.NullString `json:"clothing_style"`
	Accessories         sql.NullString `json:"accessories"`
	Skills              sql.NullString `json:"skills"`
	Incompetence        sql.NullString `json:"incompetence"`
	Talent              sql.NullString `json:"talent"`
	Weakness            sql.NullString `json:"weakness"`
	Hobbies             sql.NullString `json:"hobbies"`
	Habits              sql.NullString `json:"habits"`
	Moral               sql.NullString `json:"moral"`
	SelfControl         sql.NullString `json:"self_control"`
	Motivation          sql.NullString `json:"motivation"`
	Discouragement      sql.NullString `json:"discouragement"`
	ConfidanceLevel     sql.NullString `json:"confidance_level"`
	GreatestFear        sql.NullString `json:"greatest_fear"`
	Childhood           sql.NullString `json:"childhood"`
	ImportantPastEvents sql.NullString `json:"important_past_events"`
	BestAccomplishment  sql.NullString `json:"best_accomplishment"`
	OtherAccomplishment sql.NullString `json:"other_accomplishment"`
	Failure             sql.NullString `json:"failure"`
	Secrets             sql.NullString `json:"secrets"`
	BestMemories        sql.NullString `json:"best_memories"`
	WorstMemories       sql.NullString `json:"worst_memories"`
	StoryRole           sql.NullString `json:"story_role"`
	ShortTermGoals      sql.NullString `json:"short_term_goals"`
	LongTermGoals       sql.NullString `json:"long_term_goals"`
}

type Follow struct {
	FollowerID  int64     `json:"follower_id"`
	FollowingID int64     `json:"following_id"`
	IsFollowed  bool      `json:"is_followed"`
	CreatedAt   time.Time `json:"created_at"`
}

type Gender struct {
	ID         int16  `json:"id"`
	GenderName string `json:"gender_name"`
}

type Genre struct {
	ID        int16  `json:"id"`
	GenreName string `json:"genre_name"`
}

type Inspiration struct {
	ID       int16  `json:"id"`
	InspName string `json:"insp_name"`
}

type Item struct {
	ID                         int64          `json:"id"`
	BookID                     int64          `json:"book_id"`
	Description                sql.NullString `json:"description"`
	Purpose                    sql.NullString `json:"purpose"`
	SpecialAbilitiesProperties sql.NullString `json:"special_abilities_properties"`
	Collection                 sql.NullString `json:"collection"`
	Production                 sql.NullString `json:"production"`
	Composition                sql.NullString `json:"composition"`
	Value                      sql.NullString `json:"value"`
	Rarity                     sql.NullString `json:"rarity"`
	Occurence                  sql.NullString `json:"occurence"`
	DetectionMethods           sql.NullString `json:"detection_methods"`
	Armaments                  sql.NullString `json:"armaments"`
	Defense                    sql.NullString `json:"defense"`
	OtherEquipment             sql.NullString `json:"other_equipment"`
	History                    sql.NullString `json:"history"`
	Origin                     sql.NullString `json:"origin"`
	NotableOwners              sql.NullString `json:"notable_owners"`
}

type Note struct {
	ID        int64          `json:"id"`
	BookID    int64          `json:"book_id"`
	Name      string         `json:"name"`
	Content   sql.NullString `json:"content"`
	CreatedAt time.Time      `json:"created_at"`
}

type Permgroup struct {
	ID          int32      `json:"id"`
	Name        string     `json:"name"`
	Permissions []PermType `json:"permissions"`
}

type PublishedBook struct {
	BookID      int64     `json:"book_id"`
	AuthorID    int64     `json:"author_id"`
	IsPublished bool      `json:"is_published"`
	CreatedAt   time.Time `json:"created_at"`
}

type Quote struct {
	ID        int64          `json:"id"`
	UserID    int64          `json:"user_id"`
	Quote     sql.NullString `json:"quote"`
	Author    sql.NullString `json:"author"`
	CreatedAt time.Time      `json:"created_at"`
}

type Species struct {
	ID                       int64          `json:"id"`
	BookID                   int64          `json:"book_id"`
	Description              sql.NullString `json:"description"`
	Lifespan                 sql.NullString `json:"lifespan"`
	Height                   sql.NullString `json:"height"`
	Weight                   sql.NullString `json:"weight"`
	Diet                     sql.NullString `json:"diet"`
	SkillsAbilities          sql.NullString `json:"skills_abilities"`
	Weakness                 sql.NullString `json:"weakness"`
	ViewOnMortals            sql.NullString `json:"view_on_mortals"`
	PhysicalDescription      sql.NullString `json:"physical_description"`
	MentalDescription        sql.NullString `json:"mental_description"`
	CommonLocations          sql.NullString `json:"common_locations"`
	Habitats                 sql.NullString `json:"habitats"`
	Reproduction             sql.NullString `json:"reproduction"`
	GrowthStages             sql.NullString `json:"growth_stages"`
	MajorStages              sql.NullString `json:"major_stages"`
	MajorEthnicGroups        sql.NullString `json:"major_ethnic_groups"`
	Origin                   sql.NullString `json:"origin"`
	History                  sql.NullString `json:"history"`
	ReligiousConnections     sql.NullString `json:"religious_connections"`
	CommonCulturalInfluences sql.NullString `json:"common_cultural_influences"`
}

type User struct {
	ID             int64          `json:"id"`
	PermgroupID    int32          `json:"permgroup_id"`
	Name           string         `json:"name"`
	MiddleName     sql.NullString `json:"middle_name"`
	Surname        sql.NullString `json:"surname"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	PasswordHash   string         `json:"password_hash"`
	GenderID       int16          `json:"gender_id"`
	InspirationID  int16          `json:"inspiration_id"`
	LevelID        int16          `json:"level_id"`
	TitleID        int16          `json:"title_id"`
	AuthorTypeID   int16          `json:"author_type_id"`
	Bio            sql.NullString `json:"bio"`
	FavoriteAuthor sql.NullString `json:"favorite_author"`
	FavoriteBook   sql.NullString `json:"favorite_book"`
	LastVisited    time.Time      `json:"last_visited"`
	CreatedAt      time.Time      `json:"created_at"`
}
